#!/usr/bin/env bash
# Lataa ja purkaa GStreamer Android universal -paketti (NDK cross-link / pkg-config).
#
# Käyttö (WSL / Linux):
#   ./scripts/install-gstreamer-android.sh
#   ./scripts/install-gstreamer-android.sh --version 1.22.12 --dest ~/Android
#
# Asettaa GSTREAMER_ROOT_ANDROID ~/.config/kotisatama/android-env.sh -tiedostoon.

set -euo pipefail

GSTREAMER_VERSION="${GSTREAMER_VERSION:-1.22.12}"
DEST="${DEST:-$HOME/Android}"
ARCHIVE="gstreamer-1.0-android-universal-${GSTREAMER_VERSION}.tar.xz"
BASE_URL="https://gstreamer.freedesktop.org/data/pkg/android/${GSTREAMER_VERSION}"
INSTALL_DIR="$DEST/gstreamer-1.0-android-universal-${GSTREAMER_VERSION}"
ENV_FILE="${KOTISATAMA_ANDROID_ENV:-$HOME/.config/kotisatama/android-env.sh}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) GSTREAMER_VERSION="$2"; ARCHIVE="gstreamer-1.0-android-universal-${GSTREAMER_VERSION}.tar.xz"; BASE_URL="https://gstreamer.freedesktop.org/data/pkg/android/${GSTREAMER_VERSION}"; INSTALL_DIR="$DEST/gstreamer-1.0-android-universal-${GSTREAMER_VERSION}"; shift ;;
    --dest) DEST="$2"; INSTALL_DIR="$DEST/gstreamer-1.0-android-universal-${GSTREAMER_VERSION}"; shift ;;
    -h|--help)
      echo "Usage: $0 [--version 1.22.12] [--dest ~/Android]"
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

if [[ -d "$INSTALL_DIR/arm64/lib/pkgconfig" ]]; then
  echo "GStreamer Android already installed: $INSTALL_DIR"
else
  mkdir -p "$DEST"
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  echo "Downloading $BASE_URL/$ARCHIVE ..."
  curl -L --fail -o "$tmp/$ARCHIVE" "$BASE_URL/$ARCHIVE"
  echo "Extracting to $INSTALL_DIR ..."
  mkdir -p "$INSTALL_DIR"
  tar -xJf "$tmp/$ARCHIVE" -C "$INSTALL_DIR"
  if [[ ! -d "$INSTALL_DIR/arm64/lib/pkgconfig" ]]; then
    # Tarball may unpack ABI dirs directly into DEST.
    for abi in arm64 armv7 x86 x86_64; do
      if [[ -d "$DEST/$abi" && ! -e "$INSTALL_DIR/$abi" ]]; then
        mv "$DEST/$abi" "$INSTALL_DIR/"
      fi
    done
  fi
  if [[ ! -d "$INSTALL_DIR/arm64/lib/pkgconfig" ]]; then
    echo "Expected arm64 pkgconfig under $INSTALL_DIR" >&2
    exit 1
  fi
fi

mkdir -p "$(dirname "$ENV_FILE")"
cat >"$ENV_FILE" <<EOF
# Kotisatama Android build — generated by scripts/install-gstreamer-android.sh
export GSTREAMER_ROOT_ANDROID="$INSTALL_DIR"
export PKG_CONFIG_ALLOW_CROSS=1
# mach / build_target.py asettaa PKG_CONFIG_PATH_<target> automaattisesti.
EOF

echo ""
echo "Installed: $INSTALL_DIR"
echo "Environment: $ENV_FILE"
echo ""
echo "Lataa ennen buildia:"
echo "  source $ENV_FILE"
echo ""
echo "Tarkista arm64 pkg-config:"
echo "  PKG_CONFIG_PATH=$INSTALL_DIR/arm64/lib/pkgconfig pkg-config --modversion gstreamer-1.0"
